name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP-Direct" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $Password = ConvertTo-SecureString "ArgusTesting123!" -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $Password -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"

      - name: Start Tunnel and Show Link
        run: |
          $File = "link.txt"
          Start-Process ssh -ArgumentList "-p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 0:localhost:3389 a.pinggy.io" -RedirectStandardOutput $File
          Start-Sleep -s 15
          $Content = Get-Content $File
          if ($Content -match "a\.pinggy\.io:\d+") {
             $Addr = $matches[0]
             echo "### ðŸš€ RDP Address: $Addr" >> $env:GITHUB_STEP_SUMMARY
             echo "Username: RDP" >> $env:GITHUB_STEP_SUMMARY
             echo "Password: ArgusTesting123!" >> $env:GITHUB_STEP_SUMMARY
             # Also commit it
             $Addr | Out-File -FilePath "public_rdp.txt"
             git config --global user.name "Argus Bot"
             git config --global user.email "bot@argus.c2"
             git add public_rdp.txt
             git commit -m "RDP_READY: $Addr [skip ci]"
             git push
          }
          while($true) { Start-Sleep -s 60 }
